npx sequelize-cli model:generate --force --name users --attributes uid:string,email:string,phoneno:string,countryCode:string
npx sequelize-cli model:generate --force --name profiles --attributes username:string,bio:string,isActive:boolean,note:string,userId:integer
npx sequelize-cli model:generate --force --name stories --attributes profileId:integer,likesCount:integer,media:string,description:string
npx sequelize-cli model:generate --force --name posts --attributes profileId:integer,title:string,media:string,likesCount:integer,commentsCount:integer
npx sequelize-cli model:generate --force --name comments --attributes profileId:integer,postId:integer,comment:string,likesCount:integer
npx sequelize-cli model:generate --force --name likesOnPost --attributes profileId:integer,postId:integer
npx sequelize-cli model:generate --force --name likesOnComment --attributes profileId:integer,commentId:integer
npx sequelize-cli model:generate --force --name likesOnStory --attributes profileId:integer,storyId:integer
npx sequelize-cli model:generate --force --name hashtags --attributes tag:string,description:string,color:string,image:string
npx sequelize-cli model:generate --force --name hashtagsOnProfile --attributes profileId:integer,hashtagId:integer
npx sequelize-cli model:generate --force --name hashtagsOnStory --attributes storyId:integer,hashtagId:integer
npx sequelize-cli model:generate --force --name hashtagsOnPost --attributes postId:integer,hashtagId:integer
npx sequelize-cli model:generate --force --name userRelationCount --attributes profileId:integer,followers:integer,followings:integer
npx sequelize-cli model:generate --force --name userRelation --attributes followerProfileId:integer,beingFollowedProfileId:integer
npx sequelize-cli model:generate --force --name chats --attributes chatroomId:integer,chat:string,sendStatus:integer,sentFromProfileId:integer
npx sequelize-cli model:generate --force --name chatrooms --attributes profileId1:integer,profileId2:integer,background:string